"""empty message

Revision ID: 05c6840e8073
Revises: c67ca26edad4
Create Date: 2024-04-04 21:44:11.595063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c6840e8073'
down_revision: Union[str, None] = 'c67ca26edad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'color',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'color',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
