"""empty message

Revision ID: 07b6875f0fdf
Revises: 5514fdfaee0d
Create Date: 2024-04-04 21:56:54.891215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b6875f0fdf'
down_revision: Union[str, None] = '5514fdfaee0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'country',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'country',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
