"""empty message

Revision ID: 5514fdfaee0d
Revises: 56f56c02749b
Create Date: 2024-04-04 21:55:10.041717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5514fdfaee0d'
down_revision: Union[str, None] = '56f56c02749b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'director',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'director',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
