"""empty message

Revision ID: 56f56c02749b
Revises: 05c6840e8073
Create Date: 2024-04-04 21:48:25.420142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f56c02749b'
down_revision: Union[str, None] = '05c6840e8073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('film_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'film_id')
    # ### end Alembic commands ###
