"""empty message

Revision ID: 82cd8d16dd60
Revises: 3f47c2e8b013
Create Date: 2024-04-04 19:47:00.771917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cd8d16dd60'
down_revision: Union[str, None] = '3f47c2e8b013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
