"""empty message

Revision ID: 9f1496f423e3
Revises: 3a84d9c0de03
Create Date: 2024-04-04 22:00:37.616577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1496f423e3'
down_revision: Union[str, None] = '3a84d9c0de03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'studio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'studio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
