"""empty message

Revision ID: d1e2e007d683
Revises: 895cf8efdcaf
Create Date: 2024-04-04 22:20:45.083630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2e007d683'
down_revision: Union[str, None] = '895cf8efdcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'year',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'year',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
