version: '3.0'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  parser:
    build:
      context: ./parser
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - ./parser:/parser
    env_file:
      - .docker.env
    depends_on:
      - db

  web:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - ./api:/api
    env_file:
      - .docker.env
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8001'
    ports:
      - '8000:8001'
    depends_on:
      - parser

volumes:
  pg_data:
